[package]
name = "url_checker"
version = "0.1.0"
authors = ["KC Haley <kc@kacey.dev>"]
edition = "2021"

[dependencies]
iced = "0.3"
surf = "2.3"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
